#!/bin/bash


django() {

	project_name=$(basename $PWD)
	project_path="$PWD"
	manage_path="${project_path}/${project_name}/manage.py"

	if [ ! -f $manage_path ] ; then  # No project/manage.py
		echo "${RED}Error${NC}: Could not locate Django manage.py file."
		return -1
	fi

	if [ $# -eq 0 ] ; then
		echo "Django project ${GREEN}ready${NC}."
	fi

	while [ ! $# -eq 0 ]
		do
			case "$1" in

				--help | -h)
					echo "Django shortcut, unknown commands are forwarded to manage.py"
					echo "	-c, --check			Run Django manage.py check."
					echo "	-s, --shell			Run Django shell plus."
					echo ""
					;;

				--check | -c)
					python $manage_path check
					;;

				--shell | -s)
					python $manage_path shell_plus
					;;

				--requirements | -r)
					pip install -r $project_path/requirements.txt
					;;

				*)
					python $manage_path "$@"
					;;

			esac
			shift
		done

}
